# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/cervina/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: lts-14.14
# BEGIN ANSIBLE MANAGED BLOCK
extra-deps:
  - haskell-src-exts-1.20.3@sha256:83ae523bbec907a42c043de1f5bbf4c1554e7c3b898af07bb1ce6e80eaa282ec,4589
  - ansi-terminal-0.10.1@sha256:a2965c59699939822a5a78650d50d36131391262adadeb3ff88ba5bd2ee5b269,3226
# END ANSIBLE MANAGED BLOCK
